#pragma once
#include <juce_dsp/juce_dsp.h>

// Per PDF: "In Split mode, audio is split into high and low frequencies.
// Attenuation generated by the SideChain is only applied to the high
// frequencies, while low frequencies remain unaffected."
// Uses Linkwitz-Riley 4th-order crossover for phase-coherent split.
class CrossoverFilter
{
public:
    void prepare (double sampleRate, int samplesPerBlock);
    void reset();
    void setFrequency (float freqHz);

    // Splits input into lowOut and highOut buffers
    void process (const float* input, float* lowOut, float* highOut, int numSamples);

private:
    void updateCoefficients();

    // Two cascaded 2nd-order Butterworth = LR4
    juce::dsp::IIR::Filter<float> lpf1, lpf2;
    juce::dsp::IIR::Filter<float> hpf1, hpf2;

    double currentSampleRate = 44100.0;
    float currentFreq = 5506.0f;
};
